version: '3'

networks:
   data_security:
     external: true
      #ipam:
      #  config:
      #   - subnet: 172.62.0.0/16

services:
  mysql:
    image: mysql:8.0.20
    container_name: mysql
    ports:
      - 30306:3306
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - MYSQL_ROOT_PASSWORD=xxxx
    privileged: true
    restart: always
    volumes:
      - ./config/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./config/mysql/logs:/var/log/mysql
      - ./config/mysql/data:/var/lib/mysql
      - ./config/mysql/init:/docker-entrypoint-initdb.d/
      #- ./config/mysql/sql:/opt/sql
    networks:
      data_security:
        ipv4_address: 172.62.0.5

  gateway-service:
    build:
      context: ./java/gateway-service/
      dockerfile: Dockerfile
    image: gateway-service:1.0    
    container_name: gateway-service
    expose:
      - 8999
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
    networks:
      data_security:
        ipv4_address: 172.62.0.6

  group-module:
    build:
      context: ./java/group-module/
      dockerfile: Dockerfile
    image: group-module:1.0
    container_name: group-module
    expose:
      - 8890
    privileged: true
    restart: always
    volumes:
      - ./java/xxl-job/:/opt/
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
    networks:
      data_security:
        ipv4_address: 172.62.0.7

  core4ct-module-system:
    build:
      context: ./java/core4ct-module-system/
      dockerfile: Dockerfile
    image: core4ct-module-system:1.0
    container_name: core4ct-module-system
    expose:
      - 8080
      - 30201
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
    networks:
      data_security:
        ipv4_address: 172.62.0.8

  core4ct-gateway:
    build:
      context: ./java/core4ct-gateway/
      dockerfile: Dockerfile
    image: core4ct-gateway:1.0
    container_name: core4ct-gateway
    expose:
      - 9000
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
    networks:
      data_security:
        ipv4_address: 172.62.0.9

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./config/redis/conf/redis.conf:/etc/redis/redis.conf
      - ./config/redis/data:/data
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
    command: ["redis-server","/etc/redis/redis.conf"]
    networks:
      data_security:
        ipv4_address: 172.62.0.13

  xxl-job-admin:
    build:
      context: ./java/xxl-job-admin/
      dockerfile: Dockerfile
    image: xxl-job-admin:1.0
    container_name: xxl-job-admin
    ports:
      - 30998:8998
      #- 30988:9988
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
    networks:
      data_security:
        ipv4_address: 172.62.0.11

  nginx:
    image: nginx:1.21.3
    container_name: nginx-group
    ports:
      - 30028:80
    restart: always
    volumes:
      - ./config/nginx/:/etc/nginx/
      - ./config/html/dist/:/usr/share/nginx/html/
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
    networks:
      data_security:
        ipv4_address: 172.62.0.12

#########################nacos-config##############################
  nacos:
    image: nacos/nacos-server:v2.0.3
    container_name: nacos-standalone-mysql
    env_file:
      - ./config/nacos-docker/env/nacos-standlone-mysql.env
    volumes:
      - ./config/nacos-docker/example/standalone-logs/:/home/nacos/logs
      - ./config/nacos-docker/example/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql-nacos
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
    restart: on-failure
    networks:
      data_security:
        ipv4_address: 172.62.0.15
  mysql-nacos:
    container_name: mysql-nacos
    image: nacos/nacos-mysql:5.7
    env_file:
      - ./config/nacos-docker/env/mysql.env
    volumes:
      - ./config/nacos-docker/example/mysql:/var/lib/mysql
    ports:
      - "30063:3306"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
    networks:
      data_security:
        ipv4_address: 172.62.0.16
